name: Release

on:
  push:
    tags: [ 'v*.*.*' ]

permissions:
  contents: write
  packages: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies and test
      run: |
        npm install
        npm install -g http-server
        http-server . -p 8080 &
        sleep 3
        
        # Simple validation that endpoints work
        curl -f http://localhost:8080/ > /dev/null
        curl -f http://localhost:8080/tests/ > /dev/null
        echo "✅ Endpoints validated"
        
    - name: Generate changelog
      id: changelog
      run: |
        # Get previous tag
        PREV_TAG=$(git describe --tags --abbrev=0 HEAD~1 2>/dev/null || git rev-list --max-parents=0 HEAD)
        echo "Previous tag: $PREV_TAG"
        
        # Generate changelog
        echo "## What's Changed" > CHANGELOG.md
        git log ${PREV_TAG}..HEAD --pretty=format:"* %s (%h)" >> CHANGELOG.md
        
        # Read changelog for release notes
        CHANGELOG_CONTENT=$(cat CHANGELOG.md)
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG_CONTENT" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          # LM Studio PWA Client ${{ github.ref_name }}
          
          ${{ steps.changelog.outputs.changelog }}
          
          ## Installation
          
          1. Download `index.html` 
          2. Open in your browser
          3. Configure your LM Studio server settings
          
          ## Live Demo
          
          You can try the app directly at: https://sni10.github.io/lm-studio-pwa-client/
        draft: false
        prerelease: false
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
